issuer: https://token.actions.githubusercontent.com
subject: repo:pshickeydev/hummingbird-minecraft:workflow:.github/workflows/update-minecraft.yaml

permissions:
  contents: write
  pull_requests: write
  workflows: write
